Algoritmo "Exercicio 9A"
    // Disciplina: Computacao e Logica de Programacao
    // Professor: Flávio Mota da Cruz
    // Autor(a): Ana Clara Alves
    // Data: 03/07/2023
Var
    i, nota, soma, media: real
Inicio
    // Comandos, procedimento, funcoes, operadores, etc...
    soma <- 0
    para i de 1 ate 10 faca
        leia(nota)
        soma<-soma+nota
    fimpara
    media<-soma/10
    escreval(media)
Fimalgoritmo
